<!-- Contains required properties for osu!framework projects. -->
<Project>
  <PropertyGroup>
    <ApplicationManifest>$(MSBuildThisFileDirectory)app.manifest</ApplicationManifest>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <PropertyGroup Label="Documentation">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
