<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyTitle>osu.Game.Rulesets.ModLoader</AssemblyTitle>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>osu.Game.Rulesets.ModLoader</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <!-- ILRepack can embed Harmony into our DLL. -->
    <PackageReference Include="ILRepack.Lib.MSBuild.Task">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Lib.Harmony">
      <ExcludeAssets>runtime</ExcludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <!-- Let ILRepack see Harmony's DLL so it can merge with ours. -->
  <Target Name="CopyHarmonyToOutput" AfterTargets="ResolveReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Include="@(ReferencePath)" Condition="'%(Filename)' == '0Harmony'" />
    </ItemGroup>
  </Target>
</Project>
