name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build
        run: dotnet build -c Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: osu-modloader-with-mods
          if-no-files-found: error
          path: '*/bin/Release/net10.0/*.dll'
